FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Cash Machine

Cash Machine is an api for managing banks and customers

## Banks Collection [/banks]

### List All Banks [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Nubank",
                "creation_date": "2015-01-01T09:30:21.671Z",
                "agencies": [
                    {
                        "id": 1,
                        "number": 1001,
                        "creation_date": "2017-08-05T08:40:51.620Z",
                        "bank_id": 1,
                        "accounts": []
                    }
                ],
                "account_opening_processes": []

            }
        ]

### Create a New Bank [POST]

You may create your own bank using this action. It takes a JSON
object containing a bank and a collection of agencies.

+ Request (application/json)

        {
            "name": "Next",
            "agencies": [
                {
                "number" : 1000
                }, 
                {
                "number": 2000
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /banks/2

    + Body

            {
                "id": 2,
                "name": "Next",
                "creation_date": "2018-08-05T08:40:51.620Z",
                "agencies": [
                    {
                        "id": 1,
                        "number": 1000,
                        "creation_date": "2018-08-05T08:40:51.620Z",
                        "bank_id": 2,
                        "accounts": []
                    }, 
                    {
                        "id": 2,
                        "number": 2000,
                        "creation_date": "2018-08-05T08:40:51.620Z",
                        "bank_id": 2,
                        "accounts": []
                    }
                ]
            }